name: chatbot_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  cli_util: ^0.4.1
  dotenv: ^4.2.0
  google_gemini: ^0.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
